paired = True
procs = 1
alt_dir = False
initial_qc = True
all_qc = 'summary'
walkaway = True
front_trim = 6
mismatch = 1
R1_bases_ls = ['TCC', 'TCT']
R2_bases_ls = ['TCC', 'TCT']
non_genomic = 1
q_min = 30
q_percent = 90
end_score = 30
window = 10
rm_transit = True
