paired = True
procs = 1
alt_dir = False
initial_qc = True
all_qc = False
walkaway = True
front_trim = 6
mismatch = 1
R1_bases_ls = ['TCC', 'TCT']
R2_bases_ls = ['TCC', 'TCT']
non_genomic = 1
q_min = 30
q_percent = 95
trim_mode = False
auto_trim = False
rm_transit = True
