if (suppressMessages(!require(ggplot2))) install.packages('ggplot2', dependencies=TRUE, repos='http://cran.us.r-project.org')
suppressMessages(library(ggplot2))
if (suppressMessages(!require(reshape))) install.packages('reshape', dependencies=TRUE, repos='http://cran.us.r-project.org')
suppressMessages(library(reshape))
if (suppressMessages(!require(Hmisc))) install.packages('Hmisc', dependencies=TRUE, repos='http://cran.us.r-project.org')
suppressMessages(library(Hmisc))
