if (suppressMessages(!require(ggplot2))) install.packages('ggplot2', dependencies=TRUE)
suppressMessages(library(ggplot2))
if (suppressMessages(!require(reshape))) install.packages('reshape', dependencies=TRUE)
suppressMessages(library(reshape))
if (suppressMessages(!require(Hmisc))) install.packages('Hmisc', dependencies=TRUE)
suppressMessages(library(Hmisc))