paired = False
procs = 1
alt_dir = False
initial_qc = True
all_qc = False
walkaway = True
front_trim = 6
mismatch = 1
R1_bases_ls = ['TCC', 'TCT']
R2_bases_ls = ['TCC', 'TCT']
non_genomic = 1
end_score = 30
window = 10
min_len = 100
adapter_match = 12
q_min = 30
q_percent = 95
rm_transit = True
